# Generated by Django 4.2 on 2023-04-09 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_beta_2_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(1, 'Must contain at least 1 characters!')]),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(1, 'Must contain at least 1 characters!')]),
        ),
    ]
