# Generated by Django 4.2.2 on 2023-06-26 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_beta_2_app', '0002_movie_file_path_tvshow_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_path', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(1, 'Must contain at least 1 characters!')])),
                ('current_name', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(1, 'Must contain at least 1 characters!')])),
                ('new_name', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(1, 'Must contain at least 1 characters!')])),
                ('type', models.CharField(choices=[('Movie', 'Movie'), ('Tv-Show', 'Tv-Show')], max_length=20)),
                ('name', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(1, 'Must contain at least 1 characters!')])),
                ('renamed', models.BooleanField(default=False)),
            ],
        ),
    ]
