# Generated by Django 4.2.2 on 2023-07-25 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_beta_2_app', '0003_newfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lengths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('Movie', 'Movie'), ('Tv-Show', 'Tv-Show')], max_length=20)),
                ('watched', models.BooleanField()),
                ('name', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(1, 'Must contain at least 1 characters!')])),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
    ]
