# Generated by Django 4.2.2 on 2023-07-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_beta_2_app', '0004_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='lengths',
            name='unacquired',
            field=models.BooleanField(default=False),
        ),
    ]
